// <auto-generated />
namespace WebBackendProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202411230342118_new_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
