// <auto-generated />
namespace WebBackendProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new_dadasd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_dadasd));
        
        string IMigrationMetadata.Id
        {
            get { return "202412040210138_new_dadasd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
